=== paarnio/mollendo/xmlChecker/data/project_U1_sub1/taskflow/taskflow4.xsd
<!-- taskflow4.xsd -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!-- taskflow4.xsd version=4 2017-10-31 UPDATE: element name="points" type="xsd:string" -->
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
	taskflow4.xsd : XML checker taskflow schema for siima.model.checker.taskflow  
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="checkerTaskFlow" type="checkerTaskFlowType"/>

  <xsd:complexType name="checkerTaskFlowType">
    <xsd:sequence>
	  <xsd:element name="round" type="xsd:string"/>
	  <xsd:element name="exercise" type="xsd:string"/>
	  <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="stuZip" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="refZip" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="testCase" type="testCaseType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="comment" type="xsd:string" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <!--xsd:attribute name="defDate" type="xsd:date"/-->
  </xsd:complexType>

  <xsd:complexType name="testCaseType">
    <xsd:sequence>
	  <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="points" type="xsd:string"/>
      <xsd:element name="stuDir1" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="stuDir2" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="stuFile1" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="stuFile2" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="refDir1" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="refDir2" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="refFile1" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="refFile2" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="flow" type="flowType" minOccurs="0" maxOccurs="unbounded"/>
	  <xsd:element name="comment" type="xsd:string" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
	<xsd:attribute name="number" type="xsd:int"/>
  </xsd:complexType>
  
  <xsd:complexType name="flowType">
    <xsd:sequence>
	  <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="type" type="xsd:string"/>
      <xsd:element name="name" type="xsd:string"/>
	  <xsd:element name="inChannel" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="outChannel" type="xsd:string"  minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="operation" type="operationType" minOccurs="0" maxOccurs="unbounded"/>
	  <xsd:element name="comment" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	 </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="operationType">
    <xsd:sequence>
	  <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="type" type="xsd:string"/>
      <xsd:element name="name" type="xsd:string"/>
	  <xsd:element name="par1" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="par2" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="paramValueList" type="paramValueListType" minOccurs="0" maxOccurs="1"/>
	  <xsd:element name="return" type="xsd:string"/>
	  <xsd:element name="comment" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	 </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="paramValueListType">
    <xsd:sequence>
	  <xsd:element name="paramList" type="paramlistType" minOccurs="1" maxOccurs="1"/>
	  <xsd:element name="valueList" type="valuelistType" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
	
   <xsd:simpleType name="paramlistType">
    <xsd:list itemType="xsd:string"/>
  </xsd:simpleType>
  
  <xsd:simpleType name="valuelistType">
    <xsd:list itemType="xsd:string"/>
  </xsd:simpleType>
  
</xsd:schema>

=== paarnio/mollendo/xmlChecker/data/project_U1_sub1/taskflow/taskflow_U1EX_X_sub1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 taskflow_U1EX_X_sub1.xml validated by testcases5.xsd
-->
<checkerTaskFlow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="taskflow4.xsd">
  <round>U1</round>
  <exercise>U1EX_X</exercise>
  <description>EXTRA Comparing solution files with reference</description>
  <stuSolution>Round_U1/U1E1_1/src/CDcatalog_X_hidden.xml</stuSolution>
  <refSolution>Round_U1/U1E1_1/test/CDcatalog_3_hidden.xml</refSolution>
  <stuZip>./data/zips/Round_U1_tests/Round_U1_sub1_</stuZip>
  <refZip>./data/zips/Round_U1_tests/Round_U1_sub1_reference.zip</refZip>
   <testCase number="1">
	<description>NOTE:</description>
    <points>100</points>
    <stuDir1>Round_U1/U1E1_1/src/</stuDir1>
	<stuFile1>CDcatalog_X_hidden.xml</stuFile1>
	<!--stuFile2></stuFile2-->
	<refDir1>Round_U1/U1E1_1/test/</refDir1>
	<refFile1>CDcatalog_3_hidden.xml</refFile1>
	<!--refFile2></refFile2-->
	<!--comment>Testcase comment</comment-->
	<flow>
	  <description>The student flow</description>
	  <type>studentFlow</type>
	  <name>studentFlow1</name>
	  <!--inChannel>inC001</inChannel-->
	  <!--outChannel>stuC002</outChannel-->
	  <operation>
	    <type>ReadTxtContent</type>
        <name>ReadTxtContent1</name>
        <par1>stuDir1/stuFile1</par1>
        <!--par2>refDir1/refFile2</par2-->
		<return>stuC002</return>
      </operation>
	  <!--comment>Taskflow comment1</comment-->
	</flow>
	<flow>
	  <description>The reference flow</description>
	  <type>referenceFlow</type>
	  <name>referenceFlow1</name>
	  <!--inChannel>inC011</inChannel-->
	  <!--outChannel>refC002</outChannel-->
	  <operation>
	    <type>ReadTxtContent</type>
        <name>ReadTxtContent1</name>
        <par1>refDir1/refFile1</par1>
        <!--par2>refDir1/refFile2</par2-->
		<return>refC002</return>
      </operation>
	  <!--comment>Taskflow comment1</comment-->
	</flow>
  	<flow>
	  <description>Merging student and reference flow</description>
	  <type>mergeFlow</type>
	  <name>mergeFlow2</name>
	  <inChannel>inC002</inChannel>
	  <outChannel>outC012</outChannel>
	  <operation>
	    <type>StringCompare</type>
        <name>StringCompare1</name>
        <par1>stuC002</par1>
        <par2>refC002</par2>
		<return>merC002</return>
	    <comment>Comparing student and reference flow outputs</comment>
      </operation>
	  <!--comment>Taskflow comment1</comment-->
	</flow>
  </testCase>
</checkerTaskFlow>

=== paarnio/mollendo/xmlChecker/data/project_U1_sub1/taskflow/taskflow_U1E1_1_sub1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 taskflow3_U1E1_1_sub1.xml validated by taskflow5.xsd
-->
<checkerTaskFlow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="taskflow4.xsd">
  <round>U1</round>
  <exercise>U1E1_1</exercise>
  <description>Validation tests in Round_U1</description>
  <stuSolution>Round_U1/U1E1_1/src/CDcatalog_X_hidden.xml</stuSolution>
  <refSolution>Round_U1/U1E1_1/test/CDcatalog_3_hidden.xml</refSolution>
  <stuZip>./data/zips/Round_U1_tests/Round_U1_sub1_</stuZip>
  <refZip>./data/zips/Round_U1_tests/Round_U1_sub1_reference.zip</refZip>
   <testCase number="1">
	<description>NOTE: test-folder. The Well Formed testcase</description>
    <points>100</points>
    <stuDir1>Round_U1/U1E1_1/src/</stuDir1>
	<stuFile1>CDcatalog_X_hidden.xml</stuFile1>
	<!--stuFile2></stuFile2-->
	<refDir1>Round_U1/U1E1_1/test/</refDir1>
	<refFile1>CDcatalog_3_hidden.xml</refFile1>
	<!--refFile2></refFile2-->
	<!--comment>Testcase comment</comment-->
	<flow>
	  <description>The student flow</description>
	  <type>studentFlow</type>
	  <name>studentFlow1</name>
	  <!--inChannel>inC001</inChannel-->
	  <!--outChannel>stuC002</outChannel-->
	  <operation>
	    <type>XMLWellFormed</type>
        <name>XMLWellFormed1</name>
        <par1>stuDir1/stuFile1</par1>
        <!--par2>refDir1/refFile2</par2-->
		<return>stuC002</return>
	    <comment>XMLWellFormed operation comment1</comment>
      </operation>
	  <!--comment>Taskflow comment1</comment-->
	</flow>
	<flow>
	  <description>The reference flow</description>
	  <type>referenceFlow</type>
	  <name>referenceFlow1</name>
	  <!--inChannel>inC011</inChannel-->
	  <!--outChannel>refC002</outChannel-->
	  <operation>
	    <type>XMLWellFormed</type>
        <name>XMLWellFormed1</name>
        <par1>refDir1/refFile1</par1>
        <!--par2>refDir1/refFile2</par2-->
		<return>refC002</return>
	    <comment>XMLWellFormed operation comment2</comment>
      </operation>
	  <!--comment>Taskflow comment1</comment-->
	</flow>
  	<flow>
	  <description>Merging student and reference flow</description>
	  <type>mergeFlow</type>
	  <name>mergeFlow2</name>
	  <inChannel>inC002</inChannel>
	  <outChannel>outC012</outChannel>
	  <operation>
	    <type>StringCompare</type>
        <name>StringCompare1</name>
        <par1>refC002</par1>
        <par2>stuC002</par2>
		<return>merC002</return>
	    <comment>Comparing student and reference flow outputs</comment>
      </operation>
	  <!--comment>Taskflow comment1</comment-->
	</flow>
  </testCase>
</checkerTaskFlow>
